### ISSUE TITLE
Dockerize the project

### ISSUE THREAD

**Issue by faviasono** [geeks-of-data/knowledge-gpt#46]
The aim is create a Dockerfile to install knowledge-gpt without pip.

**Comment by eren23** [comment]
> The aim is create a Dockerfile to install knowledge-gpt without pip.

Hey, thank you for writing this issue :), totally agreed, we can prioritize this issue at some point ( sometime really soon ) if you implement such a thing earlier, feel free to open a PR though.

**Comment by eren23** [comment]
> The aim is create a Dockerfile to install knowledge-gpt without pip.

Hey, check out the current master, you can test the dockerfile yourself to see if it's working for you.
